tags:
  - "1.5.2"
  - "1.6.0"
  - "1.7.0"
  - "1.7.2"
  - "1.7.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.2.0"
  - "2.2.1"
  - "2.3.1"
  - "2.3.2"
  - "2.3.3"
  - "2.3.4"
config:
  default:
    from: "openjdk:8-jre"
    dockerize:
      version: "v0.2.0"
  1.5.2:
    elasticsearchjdbc:
      version: "1.5.2.0"
  1.6.0:
    elasticsearchjdbc:
      version: "1.6.0.1"
  1.7.0:
    elasticsearchjdbc:
      version: "1.7.0.1"
  1.7.2:
    elasticsearchjdbc:
      version: "1.7.2.1"
  1.7.3:
    elasticsearchjdbc:
      version: "1.7.3.0"
  2.0.0:
    elasticsearchjdbc:
      version: "2.0.0.1"
  2.1.0:
    elasticsearchjdbc:
      version: "2.1.0.0"
  2.1.1:
    elasticsearchjdbc:
      version: "2.1.1.2"
  2.2.0:
    elasticsearchjdbc:
      version: "2.2.0.1"
  2.2.1:
    elasticsearchjdbc:
      version: "2.2.1.0"
  2.3.1:
    elasticsearchjdbc:
      version: "2.3.1.0"
  2.3.2:
    elasticsearchjdbc:
      version: "2.3.2.0"
  2.3.3:
    elasticsearchjdbc:
      version: "2.3.3.1"
  2.3.4:
    elasticsearchjdbc:
      version: "2.3.4.1"
