tags:
  - "7"
  - "8"
  - "oracle-7"
  - "oracle-8"
config:
  default:
    bond:
      version: "0.1.3"
  7:
    from: "openjdk:7-alpine"
  8:
    from: "openjdk:8-alpine"
  oracle-7:
    from: "java:oracle-7"
  oracle-8:
    from: "java:oracle-8"
